# Generated by Django 4.2.5 on 2023-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=1000)),
                ('twitter_handle', models.CharField(blank=True, max_length=1000)),
                ('nft_link_url', models.URLField()),
                ('collection_name', models.CharField(max_length=1000)),
                ('nft_number', models.CharField(max_length=1000)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=1000)),
            ],
        ),
    ]
