# Generated by Django 4.2.5 on 2023-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=1000)),
                ('twitter_handle', models.CharField(blank=True, max_length=1000)),
                ('nft_link_url', models.URLField()),
                ('collection_name', models.CharField(max_length=1000)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NFTWalletForm',
            new_name='Wallet',
        ),
    ]
