# Generated by Django 4.2.5 on 2023-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_benefit_rename_nftwalletform_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='nft_number',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
